/**
 * MCP HTTP environment variable names (`LIGHTDASH_TOOLS_MCP_*` per ADR-0035).
 * Legacy `MCP_*` aliases are resolved in load-mcp-config.ts.
 */

export const ENV_LIGHTDASH_TOOLS_MCP_HTTP_HOST = 'LIGHTDASH_TOOLS_MCP_HTTP_HOST';
export const ENV_LIGHTDASH_TOOLS_MCP_HTTP_PORT = 'LIGHTDASH_TOOLS_MCP_HTTP_PORT';
export const ENV_LIGHTDASH_TOOLS_MCP_PUBLIC_URL = 'LIGHTDASH_TOOLS_MCP_PUBLIC_URL';
/** Rejected at config load — MCP path is persona-owned (see personas/). */
export const ENV_LIGHTDASH_TOOLS_MCP_PATH = 'LIGHTDASH_TOOLS_MCP_PATH';
export const ENV_LIGHTDASH_TOOLS_MCP_AUTH_MODE = 'LIGHTDASH_TOOLS_MCP_AUTH_MODE';
export const ENV_LIGHTDASH_TOOLS_MCP_SHARED_KEY = 'LIGHTDASH_TOOLS_MCP_SHARED_KEY';
export const ENV_LIGHTDASH_TOOLS_MCP_ALLOWED_ORIGINS = 'LIGHTDASH_TOOLS_MCP_ALLOWED_ORIGINS';
export const ENV_LIGHTDASH_TOOLS_MCP_MAX_BODY_BYTES = 'LIGHTDASH_TOOLS_MCP_MAX_BODY_BYTES';
export const ENV_LIGHTDASH_TOOLS_MCP_SESSION_TTL_MS = 'LIGHTDASH_TOOLS_MCP_SESSION_TTL_MS';
export const ENV_LIGHTDASH_TOOLS_MCP_MAX_SESSIONS = 'LIGHTDASH_TOOLS_MCP_MAX_SESSIONS';
export const ENV_LIGHTDASH_TOOLS_MCP_MAX_SESSIONS_PER_SUBJECT =
  'LIGHTDASH_TOOLS_MCP_MAX_SESSIONS_PER_SUBJECT';
export const ENV_LIGHTDASH_TOOLS_MCP_SESSION_CLEANUP_MS = 'LIGHTDASH_TOOLS_MCP_SESSION_CLEANUP_MS';
export const ENV_LIGHTDASH_TOOLS_MCP_REQUIRED_SCOPES = 'LIGHTDASH_TOOLS_MCP_REQUIRED_SCOPES';
export const ENV_LIGHTDASH_TOOLS_MCP_SCOPES_SUPPORTED = 'LIGHTDASH_TOOLS_MCP_SCOPES_SUPPORTED';
export const ENV_LIGHTDASH_TOOLS_MCP_VALIDATE_TOKEN = 'LIGHTDASH_TOOLS_MCP_VALIDATE_TOKEN';
export const ENV_LIGHTDASH_TOOLS_MCP_DANGEROUSLY_SKIP_TOKEN_VALIDATION =
  'LIGHTDASH_TOOLS_MCP_DANGEROUSLY_SKIP_TOKEN_VALIDATION';
export const ENV_LIGHTDASH_TOOLS_MCP_DANGEROUSLY_GRANT_ALL_SCOPES =
  'LIGHTDASH_TOOLS_MCP_DANGEROUSLY_GRANT_ALL_SCOPES';
export const ENV_LIGHTDASH_TOOLS_MCP_DANGEROUSLY_ALLOW_UNAUTHENTICATED =
  'LIGHTDASH_TOOLS_MCP_DANGEROUSLY_ALLOW_UNAUTHENTICATED';
export const ENV_LIGHTDASH_TOOLS_MCP_DANGEROUSLY_ALLOW_ANY_ORIGIN =
  'LIGHTDASH_TOOLS_MCP_DANGEROUSLY_ALLOW_ANY_ORIGIN';
export const ENV_LIGHTDASH_TOOLS_MCP_EXPERIMENTAL_IDENTITY_OAUTH =
  'LIGHTDASH_TOOLS_MCP_EXPERIMENTAL_IDENTITY_OAUTH';
export const ENV_LIGHTDASH_TOOLS_MCP_DANGEROUSLY_ALLOW_WRITE_IN_IDENTITY_OAUTH =
  'LIGHTDASH_TOOLS_MCP_DANGEROUSLY_ALLOW_WRITE_IN_IDENTITY_OAUTH';
export const ENV_LIGHTDASH_TOOLS_MCP_ALLOW_INSECURE_PUBLIC_URL =
  'LIGHTDASH_TOOLS_MCP_ALLOW_INSECURE_PUBLIC_URL';
export const ENV_LIGHTDASH_TOOLS_MCP_TOKEN_VALIDATION_CACHE_TTL_MS =
  'LIGHTDASH_TOOLS_MCP_TOKEN_VALIDATION_CACHE_TTL_MS';

/** Legacy aliases (deprecated). */
export const ENV_MCP_HTTP_PORT = 'MCP_HTTP_PORT';
export const ENV_MCP_SERVER_PORT = 'MCP_SERVER_PORT';
export const ENV_MCP_PUBLIC_URL = 'MCP_PUBLIC_URL';
export const ENV_MCP_AUTH_ENABLED = 'MCP_AUTH_ENABLED';
export const ENV_MCP_API_KEY = 'MCP_API_KEY';
export const ENV_MCP_ALLOWED_ORIGINS = 'MCP_ALLOWED_ORIGINS';
export const ENV_MCP_MAX_BODY_BYTES = 'MCP_MAX_BODY_BYTES';
export const ENV_MCP_SESSION_TTL_MS = 'MCP_SESSION_TTL_MS';
export const ENV_MCP_MAX_SESSIONS = 'MCP_MAX_SESSIONS';
export const ENV_MCP_SESSION_CLEANUP_MS = 'MCP_SESSION_CLEANUP_MS';
