/**
 * MCP HTTP environment variable names (`LIGHTDASH_TOOLS_MCP_*` / `LIGHTDASH_TOOLS_OAUTH_*` per ADR-0009).
 * Legacy `MCP_*` aliases are resolved in load-mcp-config.ts.
 */

export const ENV_LIGHTDASH_TOOLS_MCP_HTTP_HOST = 'LIGHTDASH_TOOLS_MCP_HTTP_HOST';
export const ENV_LIGHTDASH_TOOLS_MCP_HTTP_PORT = 'LIGHTDASH_TOOLS_MCP_HTTP_PORT';
/** Platform listen port (Cloud Run / many PaaS). Used only when dedicated MCP port env is unset. */
export const ENV_PLATFORM_PORT = 'PORT';
export const ENV_LIGHTDASH_TOOLS_MCP_PUBLIC_URL = 'LIGHTDASH_TOOLS_MCP_PUBLIC_URL';
/** Rejected at config load — MCP path is profile-owned (see profiles/). */
export const ENV_LIGHTDASH_TOOLS_MCP_PATH = 'LIGHTDASH_TOOLS_MCP_PATH';
/** Optional HTTP mount allowlist (comma-separated ProfileIds). Unset/empty → all. Stdio ignores. */
export const ENV_LIGHTDASH_TOOLS_MCP_PROFILES = 'LIGHTDASH_TOOLS_MCP_PROFILES';
/** Rejected — auth mode is inferred from credentials (ADR-0007). */
export const ENV_LIGHTDASH_TOOLS_MCP_AUTH_MODE = 'LIGHTDASH_TOOLS_MCP_AUTH_MODE';
export const ENV_LIGHTDASH_TOOLS_MCP_SHARED_KEY = 'LIGHTDASH_TOOLS_MCP_SHARED_KEY';
/** HMAC key for previewToken + destructive requestState (≥32 bytes). */
export const ENV_LIGHTDASH_TOOLS_MCP_REQUEST_STATE_KEY = 'LIGHTDASH_TOOLS_MCP_REQUEST_STATE_KEY';
export const ENV_LIGHTDASH_TOOLS_MCP_ALLOWED_ORIGINS = 'LIGHTDASH_TOOLS_MCP_ALLOWED_ORIGINS';
export const ENV_LIGHTDASH_TOOLS_MCP_MAX_BODY_BYTES = 'LIGHTDASH_TOOLS_MCP_MAX_BODY_BYTES';
export const ENV_LIGHTDASH_TOOLS_MCP_REQUIRED_SCOPES = 'LIGHTDASH_TOOLS_MCP_REQUIRED_SCOPES';
export const ENV_LIGHTDASH_TOOLS_MCP_SCOPES_SUPPORTED = 'LIGHTDASH_TOOLS_MCP_SCOPES_SUPPORTED';
export const ENV_LIGHTDASH_TOOLS_MCP_VALIDATE_TOKEN = 'LIGHTDASH_TOOLS_MCP_VALIDATE_TOKEN';
export const ENV_LIGHTDASH_TOOLS_MCP_TOKEN_VALIDATION_CACHE_TTL_MS =
  'LIGHTDASH_TOOLS_MCP_TOKEN_VALIDATION_CACHE_TTL_MS';
/** Lightdash OAuth application credentials (server-held confidential client). */
export const ENV_LIGHTDASH_TOOLS_OAUTH_CLIENT_ID = 'LIGHTDASH_TOOLS_OAUTH_CLIENT_ID';
export const ENV_LIGHTDASH_TOOLS_OAUTH_CLIENT_SECRET = 'LIGHTDASH_TOOLS_OAUTH_CLIENT_SECRET';

/** Obsolete — rejected at startup (ADR-0019 removed Redis store; others are legacy auth flags). */
export const ENV_LIGHTDASH_TOOLS_MCP_STORE = 'LIGHTDASH_TOOLS_MCP_STORE';
export const ENV_LIGHTDASH_TOOLS_MCP_REDIS_URL = 'LIGHTDASH_TOOLS_MCP_REDIS_URL';
export const ENV_LIGHTDASH_TOOLS_MCP_INSECURE_DEV = 'LIGHTDASH_TOOLS_MCP_INSECURE_DEV';
export const ENV_LIGHTDASH_TOOLS_MCP_DANGEROUSLY_SKIP_TOKEN_VALIDATION =
  'LIGHTDASH_TOOLS_MCP_DANGEROUSLY_SKIP_TOKEN_VALIDATION';
export const ENV_LIGHTDASH_TOOLS_MCP_DANGEROUSLY_GRANT_ALL_SCOPES =
  'LIGHTDASH_TOOLS_MCP_DANGEROUSLY_GRANT_ALL_SCOPES';
export const ENV_LIGHTDASH_TOOLS_MCP_DANGEROUSLY_ALLOW_UNAUTHENTICATED =
  'LIGHTDASH_TOOLS_MCP_DANGEROUSLY_ALLOW_UNAUTHENTICATED';
export const ENV_LIGHTDASH_TOOLS_MCP_DANGEROUSLY_ALLOW_ANY_ORIGIN =
  'LIGHTDASH_TOOLS_MCP_DANGEROUSLY_ALLOW_ANY_ORIGIN';
export const ENV_LIGHTDASH_TOOLS_MCP_EXPERIMENTAL_IDENTITY_OAUTH =
  'LIGHTDASH_TOOLS_MCP_EXPERIMENTAL_IDENTITY_OAUTH';
export const ENV_LIGHTDASH_TOOLS_MCP_ALLOW_INSECURE_PUBLIC_URL =
  'LIGHTDASH_TOOLS_MCP_ALLOW_INSECURE_PUBLIC_URL';

/** Legacy aliases (deprecated). */
export const ENV_MCP_HTTP_PORT = 'MCP_HTTP_PORT';
export const ENV_MCP_SERVER_PORT = 'MCP_SERVER_PORT';
export const ENV_MCP_PUBLIC_URL = 'MCP_PUBLIC_URL';
export const ENV_MCP_AUTH_ENABLED = 'MCP_AUTH_ENABLED';
export const ENV_MCP_API_KEY = 'MCP_API_KEY';
export const ENV_MCP_ALLOWED_ORIGINS = 'MCP_ALLOWED_ORIGINS';
export const ENV_MCP_MAX_BODY_BYTES = 'MCP_MAX_BODY_BYTES';

export const OAUTH_CALLBACK_PATH = '/oauth/callback' as const;
export const OAUTH_AUTHORIZE_PATH = '/oauth/authorize' as const;
export const OAUTH_TOKEN_PATH = '/oauth/token' as const;
export const OAUTH_REGISTER_PATH = '/oauth/register' as const;
/** RFC 8414 Authorization Server Metadata path on the MCP public host. */
export const OAUTH_AUTHORIZATION_SERVER_METADATA_PATH =
  '/.well-known/oauth-authorization-server' as const;
